"""
Django settings for Blog project.

Generated by 'django-admin startproject' using Django.
Updated for deployment on Render.com
"""

import os
from pathlib import Path
import dj_database_url  # Required for Render Database

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
#  SECURITY SETTINGS
# ==============================================================================

# Get SECRET_KEY from environment, or use a default for local development
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-change-me-for-production')

# Auto-detect if we are running on Render to turn off Debug mode
# If 'RENDER' env var exists, DEBUG will be False. Otherwise, True.
DEBUG = 'RENDER' not in os.environ

# Allow all hosts on Render (you can restrict this to your specific domain later)
ALLOWED_HOSTS = ['*']

# Optional: needed if you face CSRF errors on the deployed site
CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com']


# ==============================================================================
#  APPLICATION DEFINITION
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Your Apps (Make sure these match your actual folder names)
    'blog',      # Assuming you have an app named 'blog'
    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    
    # WhiteNoise is CRITICAL for serving static files (CSS/Images) on Render
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Ensures global templates folder is found
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Blog.wsgi.application'


# ==============================================================================
#  DATABASE CONFIGURATION
# ==============================================================================

# This logic automatically handles both Local (SQLite) and Production (Postgres)
DATABASES = {
    'default': dj_database_url.config(
        # If DATABASE_URL is set (on Render), use it.
        # If not (on your PC), use local SQLite.
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600
    )
}


# ==============================================================================
#  PASSWORD VALIDATION
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==============================================================================
#  INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==============================================================================
#  STATIC FILES (CSS, JavaScript, Images)
# ==============================================================================

STATIC_URL = 'static/'

# This is where collectstatic will put files for deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Extra places for collectstatic to find static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Enable WhiteNoise compression and caching support
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ==============================================================================
#  DEFAULT PRIMARY KEY FIELD TYPE
# ==============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'